version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: swifttiger-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: swifttiger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - swifttiger-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: swifttiger-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: swifttiger
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: dev-jwt-secret-key-change-in-production
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - swifttiger-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: swifttiger-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - swifttiger-network

volumes:
  postgres_data:

networks:
  swifttiger-network:
    driver: bridge