import React, { useState } from "react";
import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";
import realtimeService from "../services/realtimeService";
import { useAuth } from "../contexts/AuthContext";

const RouteSharing = ({ routeData, routeId }) => {
  const { token } = useAuth();
  const [shareUrl, setShareUrl] = useState("");
  const [isSharing, setIsSharing] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [copied, setCopied] = useState(false);

  const shareRoute = async () => {
    if (!routeData || !routeId) {
      alert("No route data available to share");
      return;
    }

    setIsSharing(true);
    try {
      const result = await realtimeService.shareRoute(
        routeId,
        routeData,
        token
      );
      setShareUrl(result.shareUrl);
    } catch (error) {
      console.error("Failed to share route:", error);
      alert("Failed to create shared route link");
    } finally {
      setIsSharing(false);
    }
  };

  const copyToClipboard = async () => {
    if (shareUrl) {
      try {
        await navigator.clipboard.writeText(shareUrl);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch (error) {
        console.error("Failed to copy to clipboard:", error);
        // Fallback for older browsers
        const textArea = document.createElement("textarea");
        textArea.value = shareUrl;
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand("copy");
        document.body.removeChild(textArea);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    }
  };

  const exportAsPDF = async () => {
    if (!routeData) {
      alert("No route data available to export");
      return;
    }

    setIsExporting(true);
    try {
      // Create a temporary div to render the route data
      const tempDiv = document.createElement("div");
      tempDiv.className = "route-export-container";
      tempDiv.style.cssText = `
        position: absolute;
        left: -9999px;
        top: -9999px;
        width: 800px;
        background: white;
        padding: 20px;
        font-family: Arial, sans-serif;
      `;

      // Generate route content
      tempDiv.innerHTML = `
        <div style="text-align: center; margin-bottom: 20px;">
          <h1 style="color: #333; margin: 0;">Route Plan</h1>
          <p style="color: #666; margin: 5px 0;">Generated on ${new Date().toLocaleDateString()}</p>
        </div>
        
        <div style="margin-bottom: 20px;">
          <h2 style="color: #444; border-bottom: 2px solid #eee; padding-bottom: 5px;">Route Summary</h2>
          <p><strong>Total Stops:</strong> ${routeData.jobs?.length || 0}</p>
          <p><strong>Estimated Duration:</strong> ${
            routeData.totalDuration
              ? `${Math.round(routeData.totalDuration / 60)} minutes`
              : "N/A"
          }</p>
          <p><strong>Total Distance:</strong> ${
            routeData.totalDistance
              ? `${Math.round((routeData.totalDistance / 1000) * 10) / 10} km`
              : "N/A"
          }</p>
        </div>
        
        <div style="margin-bottom: 20px;">
          <h2 style="color: #444; border-bottom: 2px solid #eee; padding-bottom: 5px;">Route Details</h2>
          ${
            routeData.jobs
              ?.map(
                (job, index) => `
            <div style="border: 1px solid #ddd; margin: 10px 0; padding: 15px; border-radius: 5px;">
              <h3 style="margin: 0 0 10px 0; color: #333;">Stop ${index + 1}: ${
                  job.title
                }</h3>
              <p style="margin: 5px 0; color: #666;"><strong>Customer:</strong> ${
                job.customer_name || "N/A"
              }</p>
              <p style="margin: 5px 0; color: #666;"><strong>Address:</strong> ${
                job.customer_address || "N/A"
              }</p>
              <p style="margin: 5px 0; color: #666;"><strong>Status:</strong> ${
                job.status
              }</p>
              ${
                job.estimated_duration
                  ? `<p style="margin: 5px 0; color: #666;"><strong>Duration:</strong> ${job.estimated_duration} minutes</p>`
                  : ""
              }
            </div>
          `
              )
              .join("") || "<p>No jobs in route</p>"
          }
        </div>
        
        <div style="margin-top: 30px; padding-top: 20px; border-top: 2px solid #eee; text-align: center; color: #666; font-size: 12px;">
          <p>Generated by SwiftTiger Field Service Management</p>
        </div>
      `;

      document.body.appendChild(tempDiv);

      // Convert to canvas and then to PDF
      const canvas = await html2canvas(tempDiv, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: "#ffffff",
      });

      document.body.removeChild(tempDiv);

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      const imgWidth = 210;
      const pageHeight = 295;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;

      let position = 0;

      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      pdf.save(
        `route-${routeId}-${new Date().toISOString().split("T")[0]}.pdf`
      );
    } catch (error) {
      console.error("Failed to export PDF:", error);
      alert("Failed to export route as PDF");
    } finally {
      setIsExporting(false);
    }
  };

  const exportAsImage = async () => {
    if (!routeData) {
      alert("No route data available to export");
      return;
    }

    setIsExporting(true);
    try {
      // Create a temporary div to render the route data
      const tempDiv = document.createElement("div");
      tempDiv.className = "route-export-container";
      tempDiv.style.cssText = `
        position: absolute;
        left: -9999px;
        top: -9999px;
        width: 800px;
        background: white;
        padding: 20px;
        font-family: Arial, sans-serif;
      `;

      // Generate route content (same as PDF)
      tempDiv.innerHTML = `
        <div style="text-align: center; margin-bottom: 20px;">
          <h1 style="color: #333; margin: 0;">Route Plan</h1>
          <p style="color: #666; margin: 5px 0;">Generated on ${new Date().toLocaleDateString()}</p>
        </div>
        
        <div style="margin-bottom: 20px;">
          <h2 style="color: #444; border-bottom: 2px solid #eee; padding-bottom: 5px;">Route Summary</h2>
          <p><strong>Total Stops:</strong> ${routeData.jobs?.length || 0}</p>
          <p><strong>Estimated Duration:</strong> ${
            routeData.totalDuration
              ? `${Math.round(routeData.totalDuration / 60)} minutes`
              : "N/A"
          }</p>
          <p><strong>Total Distance:</strong> ${
            routeData.totalDistance
              ? `${Math.round((routeData.totalDistance / 1000) * 10) / 10} km`
              : "N/A"
          }</p>
        </div>
        
        <div style="margin-bottom: 20px;">
          <h2 style="color: #444; border-bottom: 2px solid #eee; padding-bottom: 5px;">Route Details</h2>
          ${
            routeData.jobs
              ?.map(
                (job, index) => `
            <div style="border: 1px solid #ddd; margin: 10px 0; padding: 15px; border-radius: 5px;">
              <h3 style="margin: 0 0 10px 0; color: #333;">Stop ${index + 1}: ${
                  job.title
                }</h3>
              <p style="margin: 5px 0; color: #666;"><strong>Customer:</strong> ${
                job.customer_name || "N/A"
              }</p>
              <p style="margin: 5px 0; color: #666;"><strong>Address:</strong> ${
                job.customer_address || "N/A"
              }</p>
              <p style="margin: 5px 0; color: #666;"><strong>Status:</strong> ${
                job.status
              }</p>
              ${
                job.estimated_duration
                  ? `<p style="margin: 5px 0; color: #666;"><strong>Duration:</strong> ${job.estimated_duration} minutes</p>`
                  : ""
              }
            </div>
          `
              )
              .join("") || "<p>No jobs in route</p>"
          }
        </div>
        
        <div style="margin-top: 30px; padding-top: 20px; border-top: 2px solid #eee; text-align: center; color: #666; font-size: 12px;">
          <p>Generated by SwiftTiger Field Service Management</p>
        </div>
      `;

      document.body.appendChild(tempDiv);

      // Convert to canvas and download
      const canvas = await html2canvas(tempDiv, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: "#ffffff",
      });

      document.body.removeChild(tempDiv);

      // Download the image
      const link = document.createElement("a");
      link.download = `route-${routeId}-${
        new Date().toISOString().split("T")[0]
      }.png`;
      link.href = canvas.toDataURL();
      link.click();
    } catch (error) {
      console.error("Failed to export image:", error);
      alert("Failed to export route as image");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="bg-white rounded-lg shadow-md p-6">
      <h2 className="text-2xl font-bold text-gray-800 mb-4">
        Share & Export Route
      </h2>

      <div className="space-y-6">
        {/* Route Sharing */}
        <div className="border rounded-lg p-4">
          <h3 className="text-lg font-semibold text-gray-700 mb-3">
            Share Route
          </h3>
          <p className="text-gray-600 mb-4">
            Create a shareable link that others can use to view this route.
            Links expire after 24 hours.
          </p>

          <div className="flex flex-col sm:flex-row gap-3">
            <button
              onClick={shareRoute}
              disabled={isSharing || !routeData}
              className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
            >
              {isSharing ? "Creating Link..." : "Create Share Link"}
            </button>

            {shareUrl && (
              <div className="flex-1 flex flex-col sm:flex-row gap-2">
                <input
                  type="text"
                  value={shareUrl}
                  readOnly
                  className="flex-1 px-3 py-2 border border-gray-300 rounded-md bg-gray-50 text-sm"
                />
                <button
                  onClick={copyToClipboard}
                  className="px-4 py-2 bg-green-500 text-white rounded-md hover:bg-green-600 transition-colors"
                >
                  {copied ? "Copied!" : "Copy"}
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Route Export */}
        <div className="border rounded-lg p-4">
          <h3 className="text-lg font-semibold text-gray-700 mb-3">
            Export Route
          </h3>
          <p className="text-gray-600 mb-4">
            Export your route as a PDF document or image for offline use or
            sharing.
          </p>

          <div className="flex flex-col sm:flex-row gap-3">
            <button
              onClick={exportAsPDF}
              disabled={isExporting || !routeData}
              className="px-4 py-2 bg-red-500 text-white rounded-md hover:bg-red-600 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
            >
              {isExporting ? "Generating PDF..." : "Export as PDF"}
            </button>

            <button
              onClick={exportAsImage}
              disabled={isExporting || !routeData}
              className="px-4 py-2 bg-purple-500 text-white rounded-md hover:bg-purple-600 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
            >
              {isExporting ? "Generating Image..." : "Export as Image"}
            </button>
          </div>
        </div>

        {/* Offline Storage */}
        <div className="border rounded-lg p-4">
          <h3 className="text-lg font-semibold text-gray-700 mb-3">
            Offline Access
          </h3>
          <p className="text-gray-600 mb-4">
            Save this route for offline access when you don't have internet
            connectivity.
          </p>

          <button
            onClick={() => {
              if (routeData) {
                localStorage.setItem(
                  `offline_route_${Date.now()}`,
                  JSON.stringify({
                    ...routeData,
                    savedAt: new Date().toISOString(),
                    routeId,
                  })
                );
                alert("Route saved for offline access!");
              }
            }}
            disabled={!routeData}
            className="px-4 py-2 bg-orange-500 text-white rounded-md hover:bg-orange-600 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
          >
            Save for Offline
          </button>
        </div>
      </div>
    </div>
  );
};

export default RouteSharing;
